# Generated by Django 2.1.1 on 2018-10-31 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_tos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('teamno', models.PositiveSmallIntegerField(db_index=True, verbose_name='Team No.')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Is Completed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_from', models.GenericIPAddressField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
