# Generated by Django 2.1.7 on 2019-03-08 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ord', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(max_length=50)),
                ('image_path', models.FilePathField(blank=True, path='/home/pembo13/virt/beeme/beeme/uploads/gallery/images', recursive=True)),
                ('image_url', models.URLField(blank=True)),
                ('vimeo_id', models.CharField(blank=True, max_length=50)),
                ('youtube_id', models.CharField(blank=True, max_length=50)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Gallery')),
            ],
            options={
                'ordering': ('gallery', 'ord', 'name'),
            },
        ),
    ]
